#核心配置文件

#==============server设置=======
server:
  port: 8080
  maxHttpHeaderSize: 65536
  maxPostSize: 4194304
  servlet:
    session:
      #超时时间,Duration转换字符串方式，默认为正，负以-开头，紧接着P，
      #（字母不区分大小写）D ：天 T：天和小时之间的分隔符 H ：小时 M：分钟 S：秒 每个单位都必须是数字，且时分秒顺序不能乱。例：PT2H就是2个小时，7200秒。
      timeout: PT1H #一小时
#==========mybatis配置==========
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-locations: classpath:/mybatis-config.xml

#=============log4j2配置引入
logging:
  config: classpath:log4j2.yml

#===============数据库相关配置 begin============
database-config:
  jdbc:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-6qtkxl4y.cd.tencentcdb.com:10149/erp4m?useSSL=true&characterEncoding=utf-8
    username: erp4m
    password: 2465732jikuY
    #别名方式，扩展插件，监控统计用的filter:stat，日志用的filter:log4j，防御sql注入的filter:wall
    filters: stat
    #最大连接数
    maxActive: 300
    #初始化连接数
    initialSize: 2
    #获取连接最大等待时间
    maxWait: 60000
    #最小连接数
    minIdle: 1
    #检测连接有效性的时间间隔
    timeBetweenEvictionRunsMillis: 60000
    #连接保持空闲而不被驱逐的最长时间
    minEvictableIdleTimeMillis: 300000
    #连接有效性，检测sql
    validationQuery: SELECT 'x'
    #定时检测空闲连接有效性
    testWhileIdle: true
    #检测获取的连接的有效性
    testOnBorrow: false
    #检测要归还的连接的有效性
    testOnReturn: false
    #是否缓存preparedStatement，即PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 50
#===============数据库相关配置 end============

#===============项目相关业务配置 begin=================
custom-config:
  custom:
    #项目文件存放根路径
    fileSavePath: G:\\erpFile\\
    #nginx代理文件存放根目录
    nginxFilePath: G:\\erpFile\\mediaFile
    #nginx代理服务器IP
    nginxServerIp: localhost
    #nginx代理服务器PORT
    nginxServerPort: 80
    #nginx代理路径
    nginxServerRoot: media
    #新建用户初始密码
    defaultPassword: 123456

    #项目部署名称
    projectDeployedName: ERP4M

    #文件上传相关
    #设定文件上传的最大值 50M
    maxUploadSize: 52428800
    #设定文件上传时写入内存的最大值，如果小于这个参数不会生成临时文件，默认为10240
    maxInMemorySize: 4096
    #设定默认编码
    defaultEncoding: UTF-8

#===============项目相关业务配置 end=================

#===============redis相关配置 begin=================
redis-config:
  redis:
    #是否启用redis on-是 其它-否
    redisEnable: on
    #最大空闲数
    redisPoolMaxIdle: 20
    #最大连接数
    redisPoolMaxTotal: 50
    #最大等待毫秒数
    redisPoolMaxWaitMillis: 30000
    #redis服务器IP
    redisServerIp: localhost
    #redis服务器端口
    redisServerPort: 6379

#===============redis相关配置 end=================